<?php

/**
 * $URL: https://tarax.toyouke.com/svn/MALL/frontend/views/remedy/_form.php $
 * $Id: _form.php 4230 2020-01-26 08:05:18Z mori $
 *
 * $model:  Array of RemedyStock, generated by Remedy::stocksByPotency()
 * $key:    mixed, the key value associated with the data item
 * $index:  integer, the zero-based index of the data item in the items array returned by $dataProvider.
 * $widget: ListView, this widget instance
 */

use \yii\bootstrap\ActiveForm;
use \yii\helpers\Html;
use \yii\helpers\ArrayHelper;

foreach ($model as $key => $data) {

    $exists = \common\models\ProductMaster::find()->where(['remedy_id' => $data->remedy_id, 'potency_id' => $data->potency_id, 'vial_id' => $data->vial_id])
                   ->andWhere(['name' => ''])->all();
    if($exists){
        unset($model[$key]);
    }
}


$loadProvider = new \yii\data\ArrayDataProvider(['allModels' => $model]);

$remedy  = current($model)->remedy;
$potency = current($model)->potency;
$vial    = current($model)->vial;
$vid     = Yii::$app->request->get('vid', $vial->vial_id);
$vid     = in_array($vid, ArrayHelper::getColumn($model,'vial.vial_id')) ? $vid : $vial->vial_id ;

$config  = [
    'action' => \yii\Helpers\Url::toRoute(['/cart/remedy/add']),
    'id'     => $potency->potency_id, // remedy_id is defined, showing groups by potency
    'method' => 'get',
];

?>

<div class="remedy-potency-key<?= $key ?>" id="<?= $potency->name ?>">
    <?php $form = ActiveForm::begin($config); ?>
      <?= Html::hiddenInput('rid', $remedy->remedy_id) ?>
      <?= Html::hiddenInput('pid', $potency->potency_id) ?>

    <?php if('combination' == $potency->name): ?>
        <!-- nothing to display -->
    <?php elseif('Φ' == $potency->name): ?>
        <em>マザーチンクチャー</em>
    <?php else: ?>
        <em><?= $potency->name ?></em>
    <?php endif ?>

      <?= \yii\grid\GridView::widget([
          'tableOptions' => ['class'=>'table-condensed'],
          'showHeader'   => false,
//          'dataProvider' => new \yii\data\ArrayDataProvider(['allModels' => $model]),
          'dataProvider' => $loadProvider,
          'layout' => '{items}',
          'columns'      => [
              [
                  'label' => '',
                  'format'=> 'raw',
                  'value' => function($data, $key, $index, $column) use($vid)
                  {
                      if(! $data->in_stock && ! $data->isNewRecord)
                          return null;

                      $radio_id = sprintf('%02d%02d',$data->potency_id,$data->vial_id);
                      $checked  = ($vid == $data->vial_id);
                      return Html::radio('vid', $checked, ['class'=>'Vial','id'=> $radio_id,'value'=>$data->vial_id,'uncheck'=>null]);
                  },
              ],
              [
                  'attribute' => 'vial',
                  'format'=> 'raw',
                  'value' => function($data, $key, $index, $column)
                  {
                      $radio_id = sprintf('%02d%02d',$data->potency_id,$data->vial_id);
                      return Html::label($data->vial->name,$radio_id);
                  },
              ],
              [
                  'attribute' => 'price',
                  'format'=> 'raw',
                  'value' => function($data, $key, $index, $column)
                  {
                      $radio_id = sprintf('%02d%02d',$data->potency_id,$data->vial_id);
                      $content  = Yii::$app->formatter->asCurrency($data->price);
                      return Html::label($content,$radio_id);
                  },
                  'contentOptions' => ['class'=>'text-right'],
              ],
              [
                  'attribute' => 'in_stock',
                  'format'    => 'html',
                  'value'     => function($data){
                      if(! $data->in_stock && ! $data->isNewRecord)
                          if(($data->remedy_id == 198) && ($data->vial_id == 8)){
                              return Html::tag('span',"100ml サイズに移行しました",['class'=>'text-danger']);
                          }
                          else{
                              return Html::tag('span',"ただいま在庫切れです",['class'=>'text-danger']);
                          }
                      }
              ],
              [
                  'label' => '',
                  'format'=> 'raw',
                  'value' => function($data){
                      return $data->isLiquor() ? '<p class="btn-xs alert-warning">お酒</p>' : null;
                  },
              ],
          ],
      ]);
      ?>
    <br>

    数量
    <?= Html::dropDownList('qty', 1, [1=>1,2=>2,3=>3,4=>4,5=>5,6=>6,7=>7,8=>8,9=>9,10=>10]) ?>

    <?= Html::submitButton("カートに入れる", ['class'=>'btn btn-warning']) ?>

    <?php $form = ActiveForm::end(); ?>

    <?php
    $isLiquor = false;
    foreach($model as $stock)
        if($stock->isLiquor()){ $isLiquor = true; break; }
    ?>
    <?php if($isLiquor): ?>
      <p>※この商品はお酒です。20歳以上の年齢であることを確認できない場合には酒類を販売いたしません。</p>
    <?php endif ?>

</div>


